#!/usr/bin/env python3
"""Run VOUCH benchmark jobs on Kaggle GPU kernels.

Kaggle free tier: 30 GPU-h/week, T4x2/P100, 9-hour sessions (no mid-run
reclaims like free Colab) and a simple push/poll/output API — a much better
fit for the model-zoo jobs than ephemeral Colab VMs.

Flow per job:
  1. generate a kernel dir: kernel-metadata.json + a wrapper script that
     clones the public repo, pip-installs deps, runs the job, and copies
     results JSONs into /kaggle/working (auto-captured as kernel output);
  2. `kaggle kernels push`;
  3. poll `kaggle kernels status` until complete/error;
  4. `kaggle kernels output` to fetch results into results/.

Requires ~/.kaggle/kaggle.json (user-supplied API token) and a
phone-verified account (GPU + internet enablement).

Usage: python3 tools/kaggle_orchestrator.py [job ...]
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import time

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GIT_URL = "https://github.com/vinhqdang/VOUCH-Verifiable-Online-Unlearning-Certification-via-Hypothesis-betting"
WORKDIR = "/tmp/kaggle_kernels"

JOBS = [
    {
        "name": "vouch-zoo-a",  # Phi-1.5 TOFU + MUSE (the GPU-tier benchmark runs)
        "cmds": [
            "python experiments/run_benchmark.py --dataset tofu --seeds 0 1 2 "
            "--resume --dtype fp16 --pairs 512",
            "python experiments/run_benchmark.py --dataset muse --seeds 0 1 2 "
            "--resume --dtype fp16 --pairs 512",
        ],
        "results": ["lm_e2e_tofu_phi-1_5.json", "lm_e2e_muse_phi-1_5.json"],
    },
    {
        "name": "vouch-zoo-b",  # 2025/2026 model zoo, 1 seed each
        "cmds": [
            "python experiments/run_lm_big.py --model Qwen/Qwen3-0.6B --seeds 0 "
            "--pairs 384 --eps 0.2 --dtype fp32 --train-steps 400 --batch 4 "
            "--queries 2 --tag qwen3_06b --methods none retrain npo npo_P3_jailbreak",
            "python experiments/run_lm_big.py --model Qwen/Qwen3-4B-Instruct-2507 "
            "--seeds 0 --pairs 384 --eps 0.2 --dtype bf16 --train-steps 400 "
            "--batch 4 --queries 2 --tag qwen3_4b "
            "--methods none retrain npo npo_P3_jailbreak",
            "python experiments/run_lm_big.py "
            "--model nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16 --seeds 0 --pairs 384 "
            "--eps 0.2 --dtype bf16 --train-steps 400 --batch 4 --queries 2 "
            "--tag nemotron3_4b --methods none retrain npo npo_P3_jailbreak",
            "python experiments/run_lm_big.py --model google/gemma-4-E2B-it "
            "--seeds 0 --pairs 384 --eps 0.2 --dtype bf16 --train-steps 400 "
            "--batch 4 --queries 2 --tag gemma4 "
            "--methods none retrain npo npo_P3_jailbreak",
        ],
        "results": ["lm_e2e_qwen3_06b.json", "lm_e2e_qwen3_4b.json",
                    "lm_e2e_nemotron3_4b.json", "lm_e2e_gemma4.json"],
    },
]

WRAPPER = """\
# VOUCH benchmark job — auto-generated by tools/kaggle_orchestrator.py
import subprocess, os, shutil, glob

def sh(c):
    print('::', c, flush=True)
    r = subprocess.run(c, shell=True)
    print(':: exit', r.returncode, flush=True)
    return r.returncode

sh('pip uninstall -y torchao')
sh('pip install -q peft datasets')
sh('git clone --depth 1 {git_url} /kaggle/vouch')
os.chdir('/kaggle/vouch')
os.makedirs('results', exist_ok=True)
sh('rm -f results/lm_e2e_*.json')   # committed repo results must not pollute output
for cmd in {cmds!r}:
    sh(cmd)
for f in glob.glob('results/lm_e2e_*.json'):
    shutil.copy(f, '/kaggle/working/' + os.path.basename(f))
print('JOB DONE', flush=True)
"""


def sh(cmd, timeout=600):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True,
                       timeout=timeout)
    return r.returncode, r.stdout + r.stderr


def username():
    if os.environ.get("KAGGLE_USERNAME"):
        return os.environ["KAGGLE_USERNAME"]
    with open(os.path.expanduser("~/.kaggle/kaggle.json")) as f:
        return json.load(f)["username"]


def push(job, user):
    d = os.path.join(WORKDIR, job["name"])
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "run.py"), "w") as f:
        f.write(WRAPPER.format(git_url=GIT_URL, cmds=job["cmds"]))
    meta = {
        "id": f"{user}/{job['name']}",
        "title": job["name"],
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
    }
    with open(os.path.join(d, "kernel-metadata.json"), "w") as f:
        json.dump(meta, f, indent=2)
    rc, out = sh(f"kaggle kernels push -p {d}")
    print(out.strip(), flush=True)
    return rc == 0 and "successfully" in out.lower()


def wait(job, user, poll=180):
    ref = f"{user}/{job['name']}"
    while True:
        rc, out = sh(f"kaggle kernels status {ref}")
        line = out.strip().splitlines()[-1] if out.strip() else "?"
        print(f"[{time.strftime('%H:%M:%S')}] {line}", flush=True)
        low = out.lower()
        if "complete" in low:
            return True
        if "error" in low or "cancel" in low:
            return False
        time.sleep(poll)


def fetch(job, user):
    ref = f"{user}/{job['name']}"
    out_dir = os.path.join(WORKDIR, job["name"] + "_out")
    rc, out = sh(f"kaggle kernels output {ref} -p {out_dir}", timeout=1200)
    print(out.strip()[-300:], flush=True)
    got = []
    for name in job["results"]:
        src = os.path.join(out_dir, name)
        if os.path.exists(src):
            dst = os.path.join(REPO, "results", name)
            subprocess.run(["cp", src, dst])
            got.append(name)
    print(f"fetched: {got}", flush=True)
    # also fetch the log for diagnostics
    for lg in ("run.log", job["name"] + ".log"):
        p = os.path.join(out_dir, lg)
        if os.path.exists(p):
            subprocess.run(["cp", p, os.path.join(REPO, "results",
                                                  f"kaggle_{job['name']}.log")])
    return got


def main():
    only = sys.argv[1:] or [j["name"] for j in JOBS]
    user = username()
    print(f"kaggle user: {user}", flush=True)
    for job in JOBS:
        if job["name"] not in only:
            continue
        print(f"=== job {job['name']} ===", flush=True)
        if not push(job, user):
            print("PUSH FAILED", flush=True)
            continue
        ok = wait(job, user)
        fetch(job, user)
        print(f"=== job {job['name']} {'COMPLETE' if ok else 'FAILED'} ===",
              flush=True)


if __name__ == "__main__":
    main()
